services:
  - type: web
    name: medinomix-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_e6jAPiVpBm8Q@ep-calm-lab-a4bsqb6t-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: PORT
        value: "10000"
      - key: RENDER
        value: "true"